MOL-377: Fix wrong API key of specific channel in components
mollie/Shopware6 pull request #113
Opened 2021-04-22 09:48 UTC by boxblinkracer

if you have a specific configuration (api key) of a single sales channel, then this configuration has not been used.
it was always the MollieApiClient for the configuration for "All Sales Channels"

the origin of the problem was the singleton approach in the factory, i dont know where its created the first time, but it was with the wrong api key

i've tested: 
* before: var_dump with api key in components subscriber showed api key A (all) even though "storefront" had B
* after: var_dump shows api key B if enabled

i've improved the class itself a bit

IMPORTANT!
this factory fix could fix more problems related to refudns and shipping (where it has been used).
but it can also show problems "suddenly" when a merchant has a custom configuration that is wrong...at the moment its actually working...but wrong anyway :)

2021-04-22 10:45 UTC, barbieswimcrew approved these changes

2021-04-22 12:26 UTC, schmitzcarsten requested changes

2021-04-22 12:26 UTC, schmitzcarsten commented on src/Subscriber/CheckoutConfirmPageSubscriber.php
>      public function addDataToPage($args): void
$args is always instanceof CheckoutConfirmPageLoadedEvent ? 
If yes, please add to be type safe

2021-04-22 12:26 UTC, schmitzcarsten commented on src/Subscriber/CheckoutConfirmPageSubscriber.php
>      public function addDataToPage($args): void
and add it to the private functions too please

2021-04-23 09:23 UTC, schmitzcarsten approved these changes

2021-04-23 09:24 UTC, merged