NTR: add php minimum check to pipeline
mollie/Shopware6 pull request #116
Opened 2021-04-22 15:04 UTC by boxblinkracer

add php minimum check for php 7.2 to plugin and pipelines

2021-04-22 15:09 UTC, boxblinkracer commented on composer.json
> +  "scripts": {
here it is 
maybe wew should add a ignore or | true to it for production compatibility?

2021-04-22 16:41 UTC, barbieswimcrew approved these changes

2021-04-23 07:36 UTC, boxblinkracer commented on composer.json
> +  "scripts": {
solved

2021-04-23 07:50 UTC, schmitzcarsten requested changes

2021-04-23 07:50 UTC, schmitzcarsten commented on .github/workflows/ci_pipe.yml
> +          php-version: 7.4
wrong php version? Should be 7.2 or am i missing the point here?

2021-04-23 07:50 UTC, schmitzcarsten commented on .github/workflows/pr_pipe.yml
> +          php-version: 7.4
should be 7.2?

2021-04-23 09:00 UTC, boxblinkracer commented on .github/workflows/pr_pipe.yml
> +          php-version: 7.4
nope, this is just for dev dependency installation
the check internally is scripted in the makefile and points to php 7.2

2021-04-23 09:22 UTC, merged