MOL-359: add 6.4 compatibility
mollie/Shopware6 pull request #120
Opened 2021-04-29 15:59 UTC by schmitzcarsten

added administration routes without versioning

updated test button in administration

added solution for new rounding feature

2021-05-04 10:38 UTC, barbieswimcrew requested changes

2021-05-04 10:38 UTC, barbieswimcrew commented on src/Controller/Api/ConfigController.php
> +    private function getResponse(string $liveApiKey, string $testApiKey): JsonResponse
instead of building the JsonResponse's dataset structure inside a private method I'd prefer to create a specific response class... for example something like...

`ApiKeyResponse extends JsonResponse implements ResponseInterface`

The benefit would be that you'd easily test that by writing unit tests against that

2021-05-04 10:38 UTC, barbieswimcrew commented on src/Controller/Api/RefundController.php
> +    private function getTotalResponse(?string $orderId): JsonResponse
same like above... something like

`TotalResponse extends JsonResponse implements ResponseInterface`

would do the trick

2021-05-04 10:38 UTC, barbieswimcrew commented on src/Controller/Api/ShippingController.php
> +    public function oldShip(Request $request): JsonResponse
this method looks way to complex with all that conditions... 'd love to see that refactored

2021-05-04 11:08 UTC, boxblinkracer commented on .github/workflows/pr_pipe.yml
> -  integration:
why is this removed?
it would show if the plugin can be installed

2021-05-04 11:10 UTC, boxblinkracer commented on src/Controller/Api/RefundController.php
> +    public function refund64(Request $request): JsonResponse
i guess this is a shopware 6.4 route? maybe add a comment? :D i thought its some kind of base64 refunding

2021-05-04 11:11 UTC, boxblinkracer commented on src/Controller/Api/ShippingController.php
> +        if ($apiClient !== null) {
i dont know if this is old and moved code?
but i would rather see more early returns if its a new code

2021-05-04 11:12 UTC, boxblinkracer commented on src/Controller/Api/ShippingController.php
> +                    self::SHIPPING_DATA_KEY_TEST_MODE => true
only test mode with oauth? not without?

2021-05-04 11:12 UTC, boxblinkracer commented on src/Controller/Api/ShippingController.php
> +                    $shipmentData[self::SHIPPING_DATA_KEY_TEST_MODE] = true;
only test mode with oauth? not without?

2021-05-04 11:16 UTC, boxblinkracer commented on src/Handler/PaymentHandler.php
> +                throw new Exception('Couldn\'t create payment at mollie');
just a small one, if you use " then you wouldnt need \'

2021-05-04 11:18 UTC, boxblinkracer commented on src/Handler/PaymentHandler.php
> +                if ($mollieOrder->isPaid()) {
NO!?!
attention, this breaks payments that are authorized, or open....so all positive payments that are not "paid".
could that be?

2021-05-04 11:25 UTC, boxblinkracer commented on src/Service/OrderService.php
> +            'sku' => 'SHOPWARE ROUNDING ITEM'
small thing, but maybe avoid blanks in sku?!

2021-05-04 11:27 UTC, boxblinkracer commented on src/Validator/OrderTotalRoundingValidator.php
> +    public function validate(int $decimals, bool $roundForNet, float $interval, string $orderTaxState): bool
wouldnt it be better to rename it to something like "shouldRound"....validate might be misleading

2021-05-04 11:30 UTC, boxblinkracer commented on src/Validator/OrderTotalRoundingValidator.php
> +    public function validateShouldRound(int $decimals, bool $roundForNet, string $taxState): bool
ok i dont get the difference between these 2 functions
they are both "should consider new rounding of 6.4"
but what is the difference? i get that the second function is more about conditions than the actual value, but 2 public functions that do almos the same and almost have the same description are not so good.
option to make it private?

2021-05-04 11:32 UTC, boxblinkracer commented on tests/PHPUnit/Validator/OrderTotalRoundingValidatorTest.php
> +    public function testValidateCorrectTaxState(): void
had problems differ these 2 tests
maybe name them to something like "testValidateCorrectTaxStateNetRounding" and the upper one GrossRounding?

2021-05-04 11:33 UTC, boxblinkracer commented on src/Service/OrderService.php
> +    public function getRoundingLineItem(OrderEntity $order, string $currencyCode): array
this would be a perfect unit test, i think i didnt see one below for this?

2021-05-05 09:26 UTC, schmitzcarsten commented on src/Controller/Api/ConfigController.php
> +    private function getResponse(string $liveApiKey, string $testApiKey): JsonResponse
I agree with you. But the problem with the admin api controllers has been that the versioning of the route has been removed. So I have to implement another route without the versioning and keep the old because of backwards compatibility reasons. I just extracted the logic into private method and use them in both routes.

No time to refactor this at the moment and it is old code

2021-05-05 09:31 UTC, schmitzcarsten commented on src/Controller/Api/ShippingController.php
> +        if ($apiClient !== null) {
it is old code, see my comments to @barbieswimcrew comment for the reasons why old code became "new" code

2021-05-05 10:06 UTC, schmitzcarsten commented on src/Controller/Api/ShippingController.php
> +                    self::SHIPPING_DATA_KEY_TEST_MODE => true
old code, needs refactoring in future

2021-05-05 10:06 UTC, schmitzcarsten commented on src/Controller/Api/ShippingController.php
> +                    $shipmentData[self::SHIPPING_DATA_KEY_TEST_MODE] = true;
old code

2021-05-05 10:08 UTC, schmitzcarsten commented on src/Handler/PaymentHandler.php
> +                if ($mollieOrder->isPaid()) {
updated like discussed today

2021-05-05 10:14 UTC, schmitzcarsten commented on tests/PHPUnit/Validator/OrderTotalRoundingValidatorTest.php
> +    public function testValidateCorrectTaxState(): void
update function to private

2021-05-05 10:14 UTC, schmitzcarsten commented on src/Validator/OrderTotalRoundingValidator.php
> +    public function validateShouldRound(int $decimals, bool $roundForNet, string $taxState): bool
update function to private

2021-05-05 10:20 UTC, schmitzcarsten commented on src/Service/OrderService.php
> +    public function getRoundingLineItem(OrderEntity $order, string $currencyCode): array
will be part of future refactoring. We will add some kind of a LineItemBuilder then. unit test will follow

2021-05-05 15:16 UTC, boxblinkracer commented on .github/workflows/ci_pipe.yml
> -  e2e:
this would remove cypress

2021-05-06 06:50 UTC, schmitzcarsten commented on .github/workflows/ci_pipe.yml
> -  e2e:
added and resolved merge conflict....

2021-05-06 06:54 UTC, merged