MOL-209 - Add a link to the Mollie payment screen to orders (backend)
mollie/Shopware6 pull request #137
Opened 2021-06-03 08:05 UTC by KienerNL

Added this as a button that copies the link to the user's clipboard. Button is disabled when link is unavailable, for example, when the order has been paid already. Button is not shown for non Mollie orders.

2021-06-04 10:51 UTC, schmitzcarsten requested changes
If an order is paid or refunded you deactivate the copy link (makes sense since not necessary because order is paid)

But in case the order has been cancelled you may copy the link, but it does not work (as order is cancelled at mollie). So we have to deactivate the copy function in this cases. Please check state failed (should be deactivated too)

2021-06-04 10:51 UTC, schmitzcarsten commented on src/Service/MollieApi/Order.php
> +        $apiClient = $this->clientFactory->getClient($salesChannelId);
duplicate code from line 31 to 48 (coming from setShipment)

extract this to an own public function getMollieOrder and use this then  in both functions

2021-06-08 09:36 UTC, KienerNL commented on src/Service/MollieApi/Order.php
> +        $apiClient = $this->clientFactory->getClient($salesChannelId);
Moved to a separate function

2021-06-11 09:27 UTC, schmitzcarsten approved these changes

2021-06-11 12:03 UTC, boxblinkracer commented on src/Resources/app/administration/src/module/mollie-payments/components/mollie-test-api-key/mollie-test-api-key.html.twig
> +    <sw-button variant="context" size="x-small" link="https://www.mollie.com/dashboard/developers/api-keys">
isnt this another feature? deeplink to the api keys page?

2021-06-11 12:06 UTC, boxblinkracer commented on src/Service/MollieApi/Order.php
> +        $mollieOrder = $this->getMollieOrder($mollieOrderId, $salesChannelId);
wouldnt that be a great spot to get rid off null and use an empty string?

also, i did the featue in sw5, and as far as i can remember, once the payment or order isnt valid anymore (because it was paid) then the payment url is null anyway
so i guess the disabling doesnt make sense either...its just empty, in case it helps.
i did a placeholder instead showing "No Checkout URL available"

2021-06-14 08:10 UTC, KienerNL commented on src/Resources/app/administration/src/module/mollie-payments/components/mollie-test-api-key/mollie-test-api-key.html.twig
> +    <sw-button variant="context" size="x-small" link="https://www.mollie.com/dashboard/developers/api-keys">
Yes, which has already been merged into master. And then this branch was made up to date with master to prevent any conflicts.

2021-06-15 12:09 UTC, boxblinkracer approved these changes

2021-06-16 13:58 UTC, merged