MOL-199 Partial Refunds
mollie/Shopware6 pull request #144
Opened 2021-06-11 09:36 UTC by KienerNL

PR #89 and #134

2021-06-15 15:31 UTC, schmitzcarsten requested changes

2021-06-15 15:31 UTC, schmitzcarsten commented on src/Service/RefundService.php
> +    private function getPaymentForOrder(OrderEntity $order): Payment
extract this private function to own service. Use as parameters mollieOrderId (if empty, don't do lookup at all) and the saleschannelcontextid from order. This will make unit test easier as parameters are simple parameter types

2021-06-15 15:31 UTC, schmitzcarsten commented on src/Service/RefundService.php
> +        return array_map(function ($refund) {
what about a hydratorhere, that builds an array out of a refund. You could unit test this hydrator as separate unit test. Here everything would be a foreach and inside using hydrator

2021-06-15 15:31 UTC, schmitzcarsten commented on src/Service/RefundService.php
> +                'settlementAmount' => !is_null($refund->settlementAmount)
this is not very readable here. Why not

$array=[something];
if (!is_null($refund->settlementAmount)) {
    $array['settlementAmount']=[something]
}

2021-06-15 15:31 UTC, schmitzcarsten commented on src/Service/RefundService.php
> +            throw new MollieRefundException(
better is to have explicit Exceptions here 
perhaps CouldNotExtractMollieOrderId, then CouldNotFetchMollieOrder, then RefundsNotFound

2021-06-15 15:31 UTC, schmitzcarsten commented on src/Subscriber/PaymentStateSubscriber.php
> +        } catch (MollieRefundException $e) {
find a better exception name for the usecase

2021-06-15 15:31 UTC, schmitzcarsten commented on tests/PHPUnit/Facade/SetMollieOrderRefundedTest.php
> +        self::expectException(MollieRefundException::class);
without explicit exceptions you don't know if error is thrown in the top or the bottom. So here the unit test could be green but the error could occure at an other line of code that should not be in the  scope of this test

2021-06-15 15:31 UTC, schmitzcarsten commented on tests/PHPUnit/Service/MollieRefundsServiceTest.php
> +class MollieRefundsServiceTest extends TestCase
the class that you want to test is RefundService, so the correct unit test class name is RefundServiceTest. Perhaps  someone implements an MollieRefundsService in future ;)

2021-06-24 07:55 UTC, boxblinkracer commented on .phpstan.lvl8.neon
> +        - ./src/Hydrator/*
hi
if i got this correctly, then the hydrator folder is new?...means that all files in there are new as well?
then please ensure that your new files meet the phpstan level requirements instead of ignoring it

2021-06-24 07:59 UTC, boxblinkracer commented on src/Facade/SetMollieOrderRefunded.php
> +        $toRefund = $order->getAmountTotal() - $refunded;
im not quite sure, but i once saw a "amountRemaining" property in a mollie object...i think this is fine here, just wanted to let you know this

2021-06-24 08:16 UTC, boxblinkracer commented on src/Service/MollieApi/Order.php
> +            throw new CouldNotFetchMollieOrderException($mollieOrderId);
could you append the previous exception or add a log or anything
we never know the cause of the exception otherwise

2021-06-24 08:17 UTC, boxblinkracer commented on src/Service/MollieApi/Order.php
> +            throw new CouldNotFetchMollieOrderException($mollieOrderId);
or just remove the try catch if there should always be an order? then just fail-fast automatically?

2021-06-24 08:18 UTC, boxblinkracer commented on src/Service/MollieApi/Order.php
> +                PaymentStatus::STATUS_PAID,
doesnt klarna with orders api also have a COMPLETED state? so a different one from paid?

2021-06-24 08:26 UTC, boxblinkracer commented on src/Service/RefundService.php
> +        } catch (ApiException $e) { // Invalid resource id
i think we need to log that error right?

2021-06-24 08:26 UTC, boxblinkracer commented on src/Service/RefundService.php
> +            throw new CouldNotCancelMollieRefundException($mollieOrderId, $order->getOrderNumber(), $refundId);
i think we need to log that too?

2021-06-24 08:27 UTC, schmitzcarsten requested changes

2021-06-24 08:28 UTC, boxblinkracer commented on src/Service/RefundService.php
> +            // This may not be a Mollie order.
wouldnt that be more an exception because something is wrong?
if nothing is logged or thrown then this is a typical scenario with a fail-safe approach..but from the comment it seems as fi something might be broken? because of a missing id?

2021-06-24 08:29 UTC, boxblinkracer commented on src/Service/RefundService.php
> +            // This may not be a Mollie order.
also here, it seems as if this is no expected behaviour? then a log or exception would be nice

2021-06-24 08:30 UTC, boxblinkracer commented on src/Service/RefundService.php
> +            // This may not be a Mollie order.
also here, it seems as if this is no expected behaviour? then a log or exception would be nice

2021-06-24 08:34 UTC, boxblinkracer commented on tests/PHPUnit/Facade/SetMollieOrderRefundedTest.php
> +     * Test refunds
im happy that you provide a comment here. i do the same with every unit test.
but could you be a bit more specific on what is done in here, what is expected and things like that. because that comment doesnt have any real benefit otherwise :)

2021-06-24 08:37 UTC, boxblinkracer commented on tests/PHPUnit/Service/RefundsServiceTest.php
> +            '6.3.5.4'
does this test only cover a specific shopware version?
or what is that number and what causes it?

2021-06-24 08:41 UTC, boxblinkracer requested changes
i did a few comments

2021-06-25 09:49 UTC, KienerNL commented on tests/PHPUnit/Service/RefundsServiceTest.php
> +            '6.3.5.4'
The OrderService normally gets the `%kernel.shopware_version%` passed into in its constructor. In this test a fixed value should suffice. Also this was copied from the OrderServiceTest where @schmitzcarsten did the same.

2021-06-25 09:53 UTC, KienerNL commented on tests/PHPUnit/Facade/SetMollieOrderRefundedTest.php
> +    public function atestThatRefundIsDone(
Oops :see_no_evil:

2021-06-25 10:09 UTC, boxblinkracer commented on tests/PHPUnit/Service/RefundsServiceTest.php
> +            '6.3.5.4'
ok thx
i was asking because there is a different behaviour in the order service with shopware >= 6.4 which affects rounded items.
if that would affect refunds (which i dont think so) then you would need to do an additional 6.4-variant of your tests
otherwise feel free to mark this comment as resolved :)

2021-06-25 11:57 UTC, KienerNL commented on src/Service/RefundService.php
> +            // This may not be a Mollie order.
I was going to write an explanation why, but then I realized we probably should not even call these methods if they are not Mollie orders to begin with. So I added a check in the `sw-order-detail-base` view to check if there's a Mollie order id available, before calling these methods. These methods now log and re-throw the error if the order id cannot be found.

2021-06-25 11:57 UTC, KienerNL commented on src/Service/RefundService.php
> +            // This may not be a Mollie order.
See above.

2021-06-25 11:57 UTC, KienerNL commented on src/Service/RefundService.php
> +            // This may not be a Mollie order.
See above.

2021-06-25 11:57 UTC, KienerNL commented on tests/PHPUnit/Facade/SetMollieOrderRefundedTest.php
> +     * Test refunds
Comment has been updated.

2021-06-25 11:58 UTC, KienerNL commented on src/Service/RefundService.php
> +                $refundsArray[] = RefundHydrator::hydrate($refund);
Static removed.

2021-06-25 11:58 UTC, boxblinkracer commented on src/Service/RefundService.php
> +            // This may not be a Mollie order.
perfect thx :)

2021-06-25 11:58 UTC, KienerNL commented on src/Hydrator/RefundHydrator.php
> +    public static function hydrate(Refund $refund): array
See above.

2021-06-25 12:00 UTC, KienerNL commented on .phpstan.lvl8.neon
> +        - ./src/Hydrator/*
I've sent you a message on Slack about the errors I'm getting here

2021-06-25 12:04 UTC, KienerNL commented on src/Facade/SetMollieOrderRefunded.php
> +        $toRefund = $order->getAmountTotal() - $refunded;
Yes, but also no. It has come to my attention that some accounts are able to refund an extra amount on top of the order total. So if the order total is € 100 they can refund up to € 125. The Kiener account we use to test is able to do this, but a different account cannot. I'll be asking Lono about this in our next meet.

If the account can refund more than the order total, then this is included in the `amountRemaining` property you mentioned. Therefor I'd rather use the order total from the Shopware order to calculate how much needs to be refunded. If the customer can refund more and wants to refund more, then it would be better to use a partial refund to refund everything.

2021-06-25 12:43 UTC, KienerNL commented on .phpstan.lvl8.neon
> +        - ./src/Hydrator/*
This is now solved with @schmitzcarsten 's help

2021-07-01 11:19 UTC, KienerNL commented on tests/PHPUnit/Service/RefundsServiceTest.php
> +            '6.3.5.4'
Fortunately the refund service only uses the `getMollieOrderId` from the order service. ;)

2021-07-02 09:50 UTC, schmitzcarsten requested changes

2021-07-02 09:50 UTC, schmitzcarsten commented on src/Service/MollieApi/Order.php
> +                PaymentStatus::STATUS_PAID,
Authorized is not correct here. It should be paid or completed. see 
Kiener\MolliePayments\Service\Mollie\MolliePaymentStatus::MOLLIE_PAYMENT_COMPLETED

2021-07-02 09:50 UTC, schmitzcarsten commented on src/Service/RefundService.php
> +            return $this->orderService->getMollieOrderId($order);
remove function and use $this->orderService->getMollieOrderId direct allover this class. 

You are logging multiple errors outside in the controller

2021-07-02 09:50 UTC, schmitzcarsten commented on src/Controller/Api/RefundController.php
> +        } catch (CouldNotCreateMollieRefundException | CouldNotExtractMollieOrderIdException | CouldNotFetchMollieOrderException | PaymentNotFoundException $e) {
all errors (except ShopwareHttpException catch) are doing the same here. better catch throwable here, log it and return the json. So you would catch all errors, log them and return here

2021-07-02 09:50 UTC, schmitzcarsten commented on src/Controller/Api/RefundController.php
> +        } catch (CouldNotCancelMollieRefundException | CouldNotExtractMollieOrderIdException | CouldNotFetchMollieOrderException | PaymentNotFoundException $e) {
catch throwable here

2021-07-02 09:50 UTC, schmitzcarsten commented on src/Controller/Api/RefundController.php
> +        } catch (CouldNotExtractMollieOrderIdException | CouldNotFetchMollieOrderException | CouldNotFetchMollieRefundsException $e) {
move this catch under paymentNotFound and catch throwable here

2021-07-02 09:50 UTC, schmitzcarsten commented on src/Controller/Api/RefundController.php
> +        } catch (CouldNotExtractMollieOrderIdException | CouldNotFetchMollieOrderException $e) {
same here catch throwable and move the catch under paymentnotfoundexception

2021-07-02 09:50 UTC, schmitzcarsten commented on tests/PHPUnit/Hydrator/RefundHydratorTest.php
> +        $status = Random::getRandomArrayElement([RefundStatus::STATUS_QUEUED, RefundStatus::STATUS_PENDING, RefundStatus::STATUS_FAILED, RefundStatus::STATUS_PROCESSING, RefundStatus::STATUS_REFUNDED
forgot this?

2021-07-02 11:52 UTC, KienerNL commented on .phpstan.lvl8.neon
> +        - ./src/Hydrator/*
Yes, is removed now

2021-07-02 13:11 UTC, KienerNL commented on tests/PHPUnit/Hydrator/RefundHydratorTest.php
> +        $status = Random::getRandomArrayElement([RefundStatus::STATUS_QUEUED, RefundStatus::STATUS_PENDING, RefundStatus::STATUS_FAILED, RefundStatus::STATUS_PROCESSING, RefundStatus::STATUS_REFUNDED
Every status does not need a test case. The test is to see if the hydrator correctly returns a Refund object as an array. What test data we use for the Refund object and the expected array is largely irrelevant, but the data in both the expected array as well as the Refund object has to be the same in each separate test case. That's why both the array en Refund object are created in the same function.

2021-07-02 13:15 UTC, KienerNL commented on src/Service/MollieApi/Order.php
> +                PaymentStatus::STATUS_PAID,
Authorized is correct here. This is a `Mollie\Api\Resources\Payment` which can only return statusses from `Mollie\Api\Types\PaymentStatus`

2021-07-13 14:06 UTC, boxblinkracer approved these changes

2021-07-14 13:58 UTC, schmitzcarsten approved these changes

2021-07-15 10:17 UTC, schmitzcarsten approved these changes

2021-07-15 11:22 UTC, merged