WIP MOL-453: Refactor Webhook Notifications
mollie/Shopware6 pull request #146
Opened 2021-06-11 13:16 UTC by boxblinkracer

completely refactored the webhooks in order to correctly update all payment status possibilities

2021-06-15 11:38 UTC, boxblinkracer commented
requires personal review with @schmitzcarsten first

2021-06-15 11:52 UTC, barbieswimcrew approved these changes

2021-06-16 14:39 UTC, schmitzcarsten requested changes

2021-06-16 14:39 UTC, schmitzcarsten commented on src/Facade/Notifications/NotificationFacade.php
> +        return $this->repoOrderTransactions->search($criteria, $context)->first();
value could be null, but method should only return OrderTransactionEntity. Make it nullable

2021-06-16 14:39 UTC, schmitzcarsten commented on src/Gateway/Mollie/MollieGatewayFactory.php
> +<?php
are you using this factory anywhere? If not, please delete. I think it is over engineered, isn't it?

2021-06-16 14:39 UTC, schmitzcarsten commented on src/Resources/config/services/gateways.xml
> +        <service id="Kiener\MolliePayments\Gateway\Mollie\MollieGatewayFactory">
think it could be removed here too

2021-06-16 14:39 UTC, schmitzcarsten commented on src/Service/Order/OrderStatusUpdater.php
> +                        $transition = new Transition(OrderTransactionDefinition::ENTITY_NAME, $transaction->getId(), $transitionAction, 'stateId');
I think, we should add an authorize action in the transition handler and use it here

What about a transition that would not be possible/forbidden. We could add this logic to the transitionhandler too

2021-06-17 06:52 UTC, boxblinkracer commented on src/Gateway/Mollie/MollieGatewayFactory.php
> +<?php
yes perfect, is now not used anymore since our latest changes, thx

2021-06-17 06:53 UTC, boxblinkracer commented on src/Service/Order/OrderStatusUpdater.php
> +                        $transition = new Transition(OrderTransactionDefinition::ENTITY_NAME, $transaction->getId(), $transitionAction, 'stateId');
this transition handler is the shopware transition handler
i would now leave it this way and then it it to the handler that you are building

2021-06-17 07:24 UTC, schmitzcarsten commented on src/Service/Order/OrderStatusUpdater.php
> +                        $transition = new Transition(OrderTransactionDefinition::ENTITY_NAME, $transaction->getId(), $transitionAction, 'stateId');
i see, that's why I want mine merged. Brain fuck up where the classes exist...

2021-06-17 07:27 UTC, schmitzcarsten approved these changes

2021-06-17 07:35 UTC, merged