[MOL-497] display testmode in storefront
mollie/Shopware6 pull request #152
Opened 2021-06-21 12:19 UTC by StephanAltmann85

2021-06-22 13:10 UTC, schmitzcarsten requested changes

2021-06-22 13:10 UTC, schmitzcarsten commented on src/Subscriber/SalesChannelContextResolvedSubscriber.php
> +        return [
That is not the best way to get the needed data. If you decorate every saleschannel there is a high risk, that someone thinks that he could trust on this. But he cannot always (e.g. other saleschannel in order).

So please only add this testmodus information in account, cart and checkout (perhaps template variable/struct)

2021-06-22 13:25 UTC, StephanAltmann85 commented on src/Subscriber/SalesChannelContextResolvedSubscriber.php
> +        return [
Is it okay for you if I simply add one subscriber file like this?

```
    public static function getSubscribedEvents()
    {
        return [
            AccountOverviewPageLoadedEvent::class => 'addTestModeInformationToPages',
            AccountPaymentMethodPageLoadedEvent::class => 'addTestModeInformationToPages',
            CheckoutConfirmPageLoadedEvent::class => 'addTestModeInformationToPages',
            CheckoutFinishPageLoadedEvent::class => 'addTestModeInformationToPages'
            //...
        ];
    }

    public function addTestModeInformationToPages(PageLoadedEvent $event): void
    {
```

2021-06-23 13:15 UTC, schmitzcarsten commented on src/Subscriber/SalesChannelContextResolvedSubscriber.php
> +        return [
fine for me, yes

2021-06-23 14:58 UTC, StephanAltmann85 commented on src/Resources/snippet/nl_NL/mollie-payments.nl-NL.json
> +          "label": "(Testmodus)"
Angepasst

2021-06-23 14:59 UTC, StephanAltmann85 commented on src/Subscriber/SalesChannelContextResolvedSubscriber.php
> +        return [
Done

2021-06-24 08:55 UTC, schmitzcarsten requested changes

2021-06-24 08:55 UTC, schmitzcarsten commented on src/Subscriber/PaymentMethodSubscriber.php
>  class PaymentMethodSubscriber implements EventSubscriberInterface
don't use this subscriber. It does something totally different. Create an own subscriber and use this with your events. 

and add an unit test, because the templates need the variable

2021-06-24 08:55 UTC, schmitzcarsten commented on src/Subscriber/PaymentMethodSubscriber.php
> +            $event->getPage()->assign([ 'isMollieTestMode' => true ]);
please always use a struct when assigning data to a page        
        
        $struct = new TestModeStuct($settings->isTestMode());
        $event->getPage()->addExtension('testmode', $struct);

2021-06-24 10:58 UTC, StephanAltmann85 commented on src/Subscriber/PaymentMethodSubscriber.php
>  class PaymentMethodSubscriber implements EventSubscriberInterface
They don't, if property or extension is not available no error will be thrown. But I've added the unit tests.

2021-06-24 11:00 UTC, StephanAltmann85 commented on src/Subscriber/PaymentMethodSubscriber.php
> +            $event->getPage()->assign([ 'isMollieTestMode' => true ]);
Done

2021-06-25 08:59 UTC, schmitzcarsten requested changes

2021-06-25 08:59 UTC, schmitzcarsten commented on src/Subscriber/PaymentMethodSubscriber.php
> +use Kiener\MolliePayments\Service\SettingsService;
unused, remove pls

2021-06-25 09:01 UTC, StephanAltmann85 commented on src/Subscriber/PaymentMethodSubscriber.php
> +use Kiener\MolliePayments\Service\SettingsService;
Done

2021-06-30 11:25 UTC, schmitzcarsten approved these changes

2021-07-01 08:23 UTC, merged