MOL-623: Change selector for confirm button
mollie/Shopware6 pull request #240
Opened 2021-11-26 10:16 UTC by KienerNL

The account order edit page does not have an id attribute on it's submit button, so the components would not get initialized.

2021-11-26 15:38 UTC, boxblinkracer requested changes

2021-11-26 15:38 UTC, boxblinkracer commented on src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components-sw64.plugin.js
> -            confirmFormButton: '#confirmFormSubmit',
does it also work before 6.4? do you know that?

2021-11-26 15:38 UTC, boxblinkracer commented on tests/Cypress/cypress/integration/storefront/payment-methods/creditcard.spec.js
> +            it('Components are initialized after failed payment', () => {
can you make it less technical with something like
"Complete payment after failure with components" ...?

2021-11-26 15:38 UTC, boxblinkracer commented on tests/Cypress/cypress/integration/storefront/payment-methods/creditcard.spec.js
> +                cy.contains('**** ' + validCardNumber.substr(validCardNumber.length - 4));
can you remove this, its tested in another test
and then we have less steps in here

2021-11-26 15:38 UTC, boxblinkracer commented on tests/Cypress/cypress/integration/storefront/payment-methods/creditcard.spec.js
> +                cy.url().should('include', '/checkout/finish');
thats what you were talking about right?
so i would check debug this after the merge i guess?

2021-12-02 09:22 UTC, KienerNL commented on tests/Cypress/cypress/integration/storefront/payment-methods/creditcard.spec.js
> +                cy.url().should('include', '/checkout/finish');
Would probably be better to do as a separate ticket

2021-12-02 09:27 UTC, KienerNL commented on src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components-sw64.plugin.js
> -            confirmFormButton: '#confirmFormSubmit',
page layout, at least for the confirmOrderForm, has been the same since 6.2. It didn't exist at all in 6.1.5.

2021-12-08 11:13 UTC, merged