MOL-223 update payment methods button in administration
mollie/Shopware6 pull request #253
Opened 2021-12-14 13:47 UTC by iamreinder

2021-12-15 15:03 UTC, boxblinkracer commented on src/Resources/app/administration/src/module/mollie-payments/components/mollie-update-payment-methods/mollie-update-payment-methods.html.twig
> +        {{ $tc('sw-payment.updatePaymentMethods.button') }}
could you put that in the sub node mollie_payments (i think thats the name)

2021-12-21 15:08 UTC, iamreinder commented on src/Resources/app/administration/src/module/mollie-payments/components/mollie-update-payment-methods/mollie-update-payment-methods.html.twig
> +        {{ $tc('sw-payment.updatePaymentMethods.button') }}
Fixed it 🙂

2022-01-12 10:23 UTC, boxblinkracer commented on src/Controller/Api/PaymentMethodController.php
> +            $success = false;
i think we really want a logger in here?

also, what happens if you then throw the exception again? does it also lead to an error in the admin?
then we can make it fail fast
would it expose confidental data? then keep it as it is,

2022-01-12 10:23 UTC, boxblinkracer commented on src/Resources/app/administration/src/core/service/api/mollie-payments-payment-method.service.js
> +    constructor(httpClient, loginService, apiEndpoint = 'mollie') {
love that one, thanks for doing OOP stuff

2022-01-12 10:28 UTC, boxblinkracer requested changes
see comments

2022-01-14 07:12 UTC, iamreinder commented on src/Controller/Api/PaymentMethodController.php
> +            $success = false;
I'm not sure. It could both lead to database errors of Shopware, as well as API exceptions from Mollie. I don't exactly know which errors could be thrown and if there might be confidential data in there.

On the other hand, the user has access to the plugin configuration if it triggers this method. That wouldn't be someone who shouldn't have access to the data, right?

2022-01-14 07:12 UTC, iamreinder commented on src/Resources/app/administration/src/core/service/api/mollie-payments-payment-method.service.js
> +    constructor(httpClient, loginService, apiEndpoint = 'mollie') {
🙂 👍🏻

2022-01-14 07:17 UTC, iamreinder commented on src/Controller/Api/PaymentMethodController.php
> +            $success = false;
Correction: it could not lead to API exceptions from Mollie. It doesn't do anything with Mollie. It just works with the handler classes. So it would only be database errors of Shopware. I guess those are safe to show, right?

2022-01-14 10:07 UTC, merged