MOL-645: Fix and rebuild partial shipping
mollie/Shopware6 pull request #260
Opened 2021-12-23 16:24 UTC by KienerNL

Partial shipping in the administration has been rebuilt.

In addition, a new button has been added to allow shipping the entire order. You can find it in the new dropdown menu under the "Refund with Mollie" button.

Furthermore, support for tracking codes has been added to all shipping functions:

- Both the "Ship Order" and "Ship Item" functionalities in the administration allow you to enter tracking info. ¹
- The "human-readable" shipping API endpoints added previously now also support tracking info. ²
- An event has been added that can be used by shipment plugins (Sendcloud, PostNL, etc) to automatically ship the order and add their tracking information to Mollie. If the Shopware order was not paid with Mollie, it will do nothing of course. ³

**Tracking info**

1. If you choose to add tracking info to Mollie, then both a carrier and a tracking code need to be entered. A tracking url is optional, but nice to have.
2. The shipping API endpoints now support `trackingCarrier`, `trackingCode` and `trackingUrl` parameters. As with ¹, `trackingCarrier` and `trackingCode` are required if you specify either of them. `trackingUrl` is completely optional.
3. To add your tracking info to and ship the order with Mollie, dispatch the new `MollieOrderShipmentTrackingEvent` using the `event_dispatcher` service. As with ¹ and ² `trackingCarrier` and `trackingCode` are required, `trackingUrl` is optional. In addition, the `orderId` of the order to ship and add tracking info to is required.

2022-01-13 13:18 UTC, KienerNL commented on src/Subscriber/ShippingSubscriber.php
> +            // But if we don't catch it, the rest of the process might break.
Good idea, I should really put debug logs in more places.

2022-01-14 09:25 UTC, boxblinkracer commented on src/Event/MollieOrderShipmentTrackingEvent.php
> +        string  $trackingUrl = ''
please no optional arguments. lets stick with hard definitions

2022-01-14 09:30 UTC, boxblinkracer commented on src/Facade/MollieRefundFacade.php
> +            $amount = $order->getAmountTotal() - $this->refundService->getRefundedAmount($order);
is this a helper to have a refundAll or refundAmount?
because what i dont like is, that an accidental calling of 0 leads to a full refund.
meaning, if somewhere a cast goes wrong and a float cast leads to 0, then the full order is refunded :D 

maybe you can split the cases into 2 functions like refundAmount or refundFull? 
> IF i understand it correctly

2022-01-14 09:35 UTC, boxblinkracer commented on src/Facade/MollieShipment.php
> +        if(empty($trackingCarrier) && empty($trackingCode)) {
great conditions
would be great to have that in a unit test ;)

2022-01-14 09:39 UTC, boxblinkracer commented on src/Service/MollieApi/Shipment.php
> +                'id' => $orderLineItemId,
can we do a unit test for that array and the skippings above?

2022-01-14 09:40 UTC, boxblinkracer commented on src/Service/MollieApi/Shipment.php
> +            if ($mollieOrderLine->type === OrderLineType::TYPE_SHIPPING_FEE) {
maybe here too

2022-01-14 09:42 UTC, boxblinkracer commented on src/Struct/MollieApi/ShipmentTrackingInfoStruct.php
> +    public function toArray() {
could you add unit tests for this please?
perfect thing to verify the structure,
like the idea of this struct

2022-01-14 09:45 UTC, boxblinkracer commented on src/Subscriber/ShippingSubscriber.php
> +            MollieOrderShipmentTrackingEvent::class => 'onShipOrderWithTracking',
amazing idea.
1 thing to figure out...would a different plugin create an object of type MollieOrderShipmentTrackingEvent?
if so, then ..yeah..please switch over to an array. otherwise the shop would crash, if one decides to disable or uninstall the mollie plugin but keep PostNL or whatever plugin it uses.
i know it still would crash if one would subscribe to ::class, but if he uses a decoupled string, then its completely loose and would not crash

what do you think?

2022-01-14 09:46 UTC, boxblinkracer commented on src/Subscriber/ShippingSubscriber.php
> +            $this->logger->error($e->getMessage(), [
i dont know what is in there, but maybe add a text line before like
"Error when shipping order from Mollie Event" or something like this to locate the error also on a text-level besides introspection? so like semantic over syntax :)

2022-01-14 09:48 UTC, boxblinkracer requested changes
please see comments

2022-01-14 11:04 UTC, KienerNL commented on src/Subscriber/ShippingSubscriber.php
> +            MollieOrderShipmentTrackingEvent::class => 'onShipOrderWithTracking',
I would hope they'd use a `class_exists` before trying to implement it, instead of just blindly assuming it exists :smile: 

What do you mean by switching it to an array?

2022-01-20 13:43 UTC, KienerNL commented on src/Facade/MollieRefundFacade.php
> +            $amount = $order->getAmountTotal() - $this->refundService->getRefundedAmount($order);
Perhaps it'd be better to do this in a separate ticket, as it's already in master at the moment and this is just removing an unused parameter.

2022-01-21 16:16 UTC, merged