Mol 627: Save credit card issuer in shopware order, and display it.
mollie/Shopware6 pull request #377
Opened 2022-07-18 13:35 UTC by smemoict

I've added credit card data to the order custom data and components to display it in the admin. (With an icon!)

2022-08-01 13:25 UTC, boxblinkracer commented
Hi

this is how it looks for me? I don't see anything (NGROK is also used)

![10003___Orders___Shopware_Administration](https://user-images.githubusercontent.com/5579326/182157890-e1b43f28-0f4f-40c9-9336-c87fae33bf14.png)

2022-08-03 13:07 UTC, smemoict commented
Hey, there was indeed an error of cc data not being saved on account of being overwritten. This has been remedied and should work now.

2022-08-03 14:07 UTC, boxblinkracer commented
awesome
thank you @smemoict 
ill check it out tomorrow :)

2022-08-05 12:29 UTC, boxblinkracer commented on src/Struct/Order/OrderAttributes.php
> +    private $creditCardNumber;
can we get red if the null|string please
always make sure to return a string, if null, then its just empty
that helps for all developers that consume the data, you can just check if not empty instead of also do the NULL check.
only use null if really 3 states exist like "not defined", "empty" and "filled".
in this case its just not existing, or existing :) 
that reduces risks :)

2022-08-05 12:32 UTC, boxblinkracer commented on src/Service/OrderService.php
> +            if (isset($molliePayment->method, $molliePayment->details) && $molliePayment->method === "creditcard") {
please use constant PaymentMethod::CREDITCARD

2022-08-05 12:39 UTC, boxblinkracer commented on src/Resources/app/administration/package.json
> +  "name": "mollie-shopware6-administration-tests",
not quite sure why this file is touched? i see the raw-loader
you also added a webpack config, so isnt that then a prod-dependency and not a dev one? this file was originally meant for the testing
...im also wondering why its needed...i think there are already images existing in the administration...so i dont get why this has been added :) maybe you can explain

2022-08-05 12:39 UTC, boxblinkracer requested changes
its now working on my side
thank you :)
started code review and found a few small things, please see comments

2022-08-08 07:21 UTC, smemoict commented on src/Resources/app/administration/package.json
> +  "name": "mollie-shopware6-administration-tests",
This was a formatting commit that slipped though, I think I reverted it.

2022-08-08 10:40 UTC, smemoict commented on src/Service/OrderService.php
> +            if (isset($molliePayment->method, $molliePayment->details) && $molliePayment->method === "creditcard") {
agreed, done

2022-08-08 10:40 UTC, smemoict commented on src/Struct/Order/OrderAttributes.php
> +    private $creditCardNumber;
Sounds good

2022-08-31 10:30 UTC, merged