MOL-949: remove payment url custom field
mollie/Shopware6 pull request #451
Opened 2022-11-11 12:09 UTC by daniel-memo-ict

2022-11-23 21:56 UTC, boxblinkracer commented on src/Facade/MolliePaymentDoPay.php
> +        $checkoutURL = $mollieOrder->getCheckoutUrl() ?? $transactionStruct->getReturnUrl();
i guess we can remove the TODO? :) 
still wondering, why is checkout url used or return URL? why 2 different ones? could you add it as comment if you know?

2022-11-23 21:56 UTC, boxblinkracer requested changes
please see comments

2022-11-24 11:44 UTC, daniel-memo-ict commented on src/Facade/MolliePaymentDoPay.php
> +        $checkoutURL = $mollieOrder->getCheckoutUrl() ?? $transactionStruct->getReturnUrl();
I'm not sure but I'm gonna guess it's a fallback for a case that technically could happen, but practically never happens? `getCheckoutUrl()` technically can return null, even though in practice that never happens, and I think whoever wrote that added the Shopware return url as a fallback, on the off chance that it does happen.

2022-12-14 11:26 UTC, boxblinkracer commented on src/Facade/MolliePaymentDoPay.php
> +        $checkoutURL = $mollieOrder->getCheckoutUrl() ?? $transactionStruct->getReturnUrl();
checkout URL can be null on apple pay payments with a token
its indeed null or empty in that case because a redirect doesnt make sense.
also with earlier non-3d secure cards (which are deprecated anyway)
but i think the code is good. could you add the info with apple pay and empty checkoutURLs...that should be fine then
another thing that pops up is..checkout URL is empty once the paymment is completed. what if we would re-visit this page? in the earlier version it redirected us to our history data...will this still work? is it still a thing?

2023-01-12 12:14 UTC, daniel-memo-ict commented on src/Facade/MolliePaymentDoPay.php
> +        $checkoutURL = $mollieOrder->getCheckoutUrl() ?? $transactionStruct->getReturnUrl();
Comment has been updated.

> another thing that pops up is..checkout URL is empty once the paymment is completed. what if we would re-visit this page? in the earlier version it redirected us to our history data...will this still work? is it still a thing?

If the payment has been completed they shouldn't be able to come back here.

2023-02-07 09:27 UTC, merged