MOL-864 Full Refund with Flow Builder + Refund Manager after partial refund throws error
mollie/Shopware6 pull request #516
Opened 2023-02-22 12:31 UTC by smemoict

2023-02-28 16:09 UTC, boxblinkracer requested changes
please see comments, thank you

2023-02-28 16:09 UTC, boxblinkracer commented on src/Components/RefundManager/RefundManager.php
> +        foreach ($refunds as $refund) {
so i tried to figure out what this does,
i think its calculating what is already refunded to substract it?
so a) could you also add comments
and b) doesnt it look like the code form the RefundDataBuilder ? there is already such a logic to get the refunded values from composition and mollie line item quantities

could you double check and reuse that if so?

2023-03-02 09:00 UTC, smemoict commented on src/Components/RefundManager/RefundManager.php
> +    public function getOrderLineId($lineItem): string
Agreed, it has been integrated with existing code

2023-03-02 09:01 UTC, smemoict commented on src/Components/RefundManager/RefundManager.php
> +        foreach ($refunds as $refund) {
Agreed, re-using.

2025-02-20 15:29 UTC, boxblinkracer commented
hey hey
thank you so much for this my friend 

i cant remember why it was never been finished, if it was our fault im so sorry
so we did it with the current version of the plugin, which means i would close this PR

if something is not working, just let us know :)

2025-02-20 15:29 UTC, closed without merging