MOL-1166: Show warning for high order lifetime days
mollie/Shopware6 pull request #586
Opened 2023-06-09 10:13 UTC by BlackScorp

This PR shows a warning if the order lifetime days is higher than 28, because Klarna has a limit of 28 days (could be higher depends on merchant)

And shows an error if there are more than 100 days

2023-06-26 08:09 UTC, boxblinkracer commented on src/Resources/app/administration/src/module/mollie-payments/components/mollie-pluginconfig-section-order-lifetime-warning/index.js
> +                this.oderLifeTimeLimitReached = orderLifeTime > maximumOrderLifeTime;
should we do a jest test for this?

2023-06-26 08:10 UTC, boxblinkracer commented on src/Resources/app/administration/src/module/mollie-payments/components/mollie-pluginconfig-section-order-lifetime-warning/index.js
> +                    this.oderLifeTimeLimitReached = orderLifeTime > maximumOrderLifeTime;
duplicate code right?

2023-06-26 08:13 UTC, boxblinkracer commented on tests/Cypress/cypress/e2e/admin/plugin-config.cy.js
> +        it('Display order lifetime days warning', () => {
C1097313 for testrail

2023-06-28 11:08 UTC, boxblinkracer commented on src/Resources/app/administration/src/module/mollie-payments/components/mollie-pluginconfig-section-order-lifetime-warning/services/OderLifeTimeLimitDetectorService.js
> +    checkValue(orderLifeTime) {
can you provide the variable in the methods directly
otherwise this would be a risk if one would not call the checkValue before :)

2023-06-28 11:08 UTC, boxblinkracer requested changes
see comments

2023-06-28 12:03 UTC, BlackScorp commented on src/Resources/app/administration/src/module/mollie-payments/components/mollie-pluginconfig-section-order-lifetime-warning/services/OderLifeTimeLimitDetectorService.js
> +    checkValue(orderLifeTime) {
done

2023-06-28 12:05 UTC, merged