FIX: ContextPersister requires saleschannelId in 6.3.5
mollie/Shopware6 pull request #69
Opened 2021-02-08 15:51 UTC by milan-kiener

This fixes an issue with Apple Pay Direct and the upcoming PayPal Shortcut in 6.3.5+

2021-02-08 16:37 UTC, barbieswimcrew approved these changes

2021-02-11 07:35 UTC, schmitzcarsten requested changes

2021-02-11 07:35 UTC, schmitzcarsten commented on src/Service/CustomerService.php
> +            ],
I think this will break old shopware versions. The method signature of the save function does not have the new 2 parameters (checked shopware 6.1)
Would you please check this? And if I'm right, please implement a solution that works in all shopware versions

2021-02-12 14:35 UTC, milan-kiener commented on src/Service/CustomerService.php
> +            ],
It should be compatible with older versions of shopware* because it's always allowed to pass in extra parameters even if a function does not expect them, you could still be requesting the extra params using `func_get_args()` after all. Yes your IDE will whine about it, but it doesn't actual break anything.

The only problematic version, hence the asterisk, is 6.3.3.x. The order of parameters for the context persister is:
- In 6.3.2 and lower: token, parameters.
- In 6.3.3: token, parameters, **customerId**
- In 6.3.4 and higher: token, parameters, salesChannelId, **customerId**

The only thing I can think of to include compatibility with 6.3.3, is to have an if else where we check for the same feature flag as shopware does in the context persister, which is NEXT_10058. But it's not recommended to ship plugins that rely on feature flags...

2021-02-14 13:30 UTC, schmitzcarsten commented on src/Service/CustomerService.php
> +            ],
@milan-kiener ok, good that we found this issue. The problem here is, that if we would leave the code as it is, it will break shopware 6.3.3.x. 
So we need a solution to recognize which shopware version is used and if 6.3.3.x we have to call the method with other parameter order.
I agree that we shouldn't use feature flags. So we have to find out which shopware version is used.

2021-02-15 16:32 UTC, schmitzcarsten commented on src/Service/CustomerService.php
> +            ],
@milan-kiener perhaps adding shopware version per DI solves the problem. 
<argument>%kernel.shopware_version%</argument> should do the trick. But I don't know if we get all minor versions with this.
If so, we may use the proposed if switch here and are safe in all shopware versions

2021-02-16 11:05 UTC, schmitzcarsten approved these changes

2021-02-16 11:10 UTC, merged