MOL-142: tax calculation for mollie api
mollie/Shopware6 pull request #71
Opened 2021-02-10 13:01 UTC by schmitzcarsten

2021-02-10 15:02 UTC, barbieswimcrew approved these changes

2021-02-10 16:02 UTC, boxblinkracer commented on src/Service/ApiTaxCalculator.php
> +        return round($totalAmount, 2) * ($vatRate / (100 + $vatRate));
aehm...wouldnt the vatAmount be 3 digits? maybe round that end result one more time?
`24.99 * (16 / 116) = 3,4468....`

2021-02-10 16:03 UTC, boxblinkracer commented on src/Service/OrderService.php
> +                throw new MissingPriceLineItemException($item->getId());
great exception handling, bedankt

2021-02-10 16:03 UTC, boxblinkracer commented on src/Service/OrderService.php
> +                throw new MissingPriceLineItemException($item->getId());
but...you could just throw $e....would be more correct?

2021-02-10 16:07 UTC, boxblinkracer commented on src/Service/OrderService.php
> +                'vatAmount' => $molliePreparedApiPrices['vatAmount'],
i think it would be more reliable to have a struct object instead of array...

2021-02-10 16:08 UTC, boxblinkracer commented on src/Service/OrderService.php
> +            'vatRate' => number_format($vatRate, 2, '.', '')
attention, number_forma does an implicit rounding or truncation (i forgot) but it onece screwed up something :D

2021-02-10 16:10 UTC, boxblinkracer commented on src/Service/OrderService.php
> +        $vatAmount = $this->apiTaxCalculator->calculateTaxAmount($lineItemTotalPrice, $vatRate);
i know the function is internally rounding the line item total price, problem is
that in line 327 it would be used without any rounding (or with number_format which might only truncate)

so i would rather see an explicit rounding here in 322 of all base values
then maybe the vatAmount rounding, and these values should be inserted below 

that code looks like sw5 which had these bugs and had to be changed

also if its just 1 line, i would think about removing the apiTaxCalculator function and only adding it here within a "transparent" algorithm and workflow

2021-02-10 16:12 UTC, boxblinkracer commented on tests/Fake/LoggerFake.php
> +    public function emergency($message, array $context = array())
i think there would be a ready to use NullLogger....just to let you know

2021-02-10 16:13 UTC, boxblinkracer commented on tests/Service/OrderServiceTest.php
> +        $this->assertSame($expected, $actual);
really really down to the core...but i think value is based on string, where "same" might not be what you want to check? maybe more "equals"?

2021-02-10 16:16 UTC, boxblinkracer commented on tests/Service/OrderServiceTest.php
> +            ],
please try this (MOL-70)
* expectedVatAmount = 1.89
* unitPrice = 1.1368
* taxRate = 16
* quantity = 12

2021-02-10 16:17 UTC, boxblinkracer requested changes
please see comments. some optional but some definitely a good thing, also the unit test please

2021-02-11 09:55 UTC, schmitzcarsten commented on src/Service/ApiTaxCalculator.php
> +        return round($totalAmount, 2) * ($vatRate / (100 + $vatRate));
the api tax calculator has been deleted and the algorithm has been implemented in orderservice directly. The rounding has been extracted to temporary variables for better readability

2021-02-11 09:56 UTC, schmitzcarsten commented on src/Service/OrderService.php
> +                'vatAmount' => $molliePreparedApiPrices['vatAmount'],
the whole implementation has to be refactored in near future. This is only a fix for now

2021-02-11 09:57 UTC, schmitzcarsten commented on tests/Fake/LoggerFake.php
> +    public function emergency($message, array $context = array())
refactored

2021-02-11 09:59 UTC, schmitzcarsten commented on tests/Service/OrderServiceTest.php
> +        $this->assertSame($expected, $actual);
both values $expected and $actual are strings. So same should be correct here, equals would except floats because of implicit cast

2021-02-11 09:59 UTC, schmitzcarsten commented on tests/Service/OrderServiceTest.php
> +            ],
added

2021-02-11 10:59 UTC, boxblinkracer approved these changes

2021-02-11 11:55 UTC, merged