MOL-159: do not send lifetimedays if they are not set in config
mollie/Shopware6 pull request #76
Opened 2021-02-16 12:59 UTC by BlackScorp

made the methods getOrderLifetimeDays and getOrderLifetimeDate nullable.

in the File Handler/Method/PaymentHandler.php

there is following line
` 
$dueDate = $settings->getOrderLifetimeDate();

            if ($dueDate !== null) {
                $orderData[self::FIELD_EXPIRES_AT] = $dueDate;
            }
`
so i assume if the $dueDate is not set it will not send to the api request. if the date is not configured in the plugin settings, this method will return null

2021-02-16 13:03 UTC, barbieswimcrew requested changes

2021-02-16 13:03 UTC, barbieswimcrew commented on phpunit.xml
> +      <directory>./oder kotests</directory>
this directory doesn't look valid to me... could you please re-check that?

2021-02-16 13:05 UTC, BlackScorp commented on phpunit.xml
> +      <directory>./oder kotests</directory>
oh sorry, changed of course

2021-02-16 14:00 UTC, barbieswimcrew approved these changes

2021-02-18 19:28 UTC, schmitzcarsten approved these changes

2021-02-18 19:29 UTC, merged