PISHPS-328: added ApplePayValidationAllowList
mollie/Shopware6 pull request #790
Opened 2024-07-09 11:39 UTC by m-muxfeld-diw

…ault saleschannel urls, integrated allow list into applepay validate route

2024-07-09 12:20 UTC, boxblinkracer commented on src/Resources/config/config.xml
> +            <name>ApplePayValidationAllowList</name>
and please use applePayDirect as prefix, because non-direct would be another payment method

2024-07-09 12:21 UTC, boxblinkracer commented on src/Resources/config/config.xml
> +            <label lang="de-DE">Zulässige Domains für die Apple Pay Validierung</label>
could you add something like "leave empty if no separate headless ...stuff with additional domain is used"
or "only required if a custom domain is used for a headless storefront"
just to avoid people getting confused and thinking this needs to be added
one of the mollie usps is a plugn'play approach without lots of required configs

2024-07-09 12:23 UTC, boxblinkracer commented on src/Components/ApplePayDirect/ApplePayDirect.php
> +    public function validateValidationUrl(string $validationUrl): string
validate DOMAIN? or?
validation URL is something else, we need to validate the domain
which also means we should rename the whole member variables and probably classes?
(we can talk in zoom if you want)

2024-07-09 12:23 UTC, m-muxfeld-diw commented on src/Resources/config/config.xml
> +            <label lang="de-DE">Zulässige Domains für die Apple Pay Validierung</label>
currently it is always required but the ApplePayConfigSubscriber adds all associated domains of the shop automatically to the configuration on install/update

2024-07-09 12:24 UTC, boxblinkracer commented on src/Components/ApplePayDirect/ApplePayDirect.php
> +    public function validateValidationUrl(string $validationUrl): string
also why do we require a string return value? its no "getter" it just validates with exception approach, meaning void is totally fine?
so sanitizing might be better as a second function? function naming and content is a bit different i think?

2024-07-09 12:25 UTC, boxblinkracer commented on src/Components/ApplePayDirect/Gateways/ApplePayValidationUrlAllowListGateway.php
> +        $allowList = $this->systemConfigService->get('MolliePayments.config.ApplePayValidationAllowList');
please use our own SettingsService to avoid duplicate hardcoded config strings

2024-07-09 12:29 UTC, boxblinkracer commented on src/Components/ApplePayDirect/Subscriber/ApplePayConfigSubscriber.php
> +    public function __construct(SystemConfigService $systemConfigService, EntityRepository $salesChannelDomainRepository)
i dont see any benefit in this?
we get the string anyway if we use the  settings service when we need this?!

2024-07-09 12:31 UTC, boxblinkracer commented on tests/PHPUnit/Components/ApplePayDirect/Gateways/ApplePayValidationUrlAllowListGatewayTest.php
> +        $allowListString = 'https://example.com,https://example-url.org';
great test
could you also add a simple domain or a separate unit test where it loads just domains without https scheme?

2024-07-09 12:32 UTC, boxblinkracer commented on tests/PHPUnit/Components/ApplePayDirect/Models/Collections/ApplePayValidationUrlAllowListTest.php
> +    public function canDetermineIfValueIsContainedInList(): void
attention
tests without "test" prefix will not be executed

2024-07-09 12:33 UTC, boxblinkracer commented on tests/PHPUnit/Components/ApplePayDirect/Services/ApplePayValidationUrlSanitizerTest.php
> +            'keeps http value if provided' => ['http://example.com', 'http://example.com/'],
not quite sure if trailing slash is good?

2024-07-09 12:33 UTC, boxblinkracer commented on tests/PHPUnit/Service/ApplePayDirect/ApplePayDirectTest.php
> +        $this->expectExceptionMessage('The Apple Pay validation URL allow list can not be empty. Please check the configuration.');
thats wrong, it can be empty

2024-07-09 12:35 UTC, boxblinkracer requested changes
comments

2024-07-11 06:41 UTC, boxblinkracer commented on src/Components/ApplePayDirect/Gateways/ApplePayDirectDomainAllowListGateway.php
> +        $allowList = $settings->applePayDirectDomainAllowList ?? '';
achtung, hier sollte ein getter das schon machen, direkt member-access sollte nicht erlaubt sein

2024-07-11 06:44 UTC, boxblinkracer commented on src/Components/ApplePayDirect/Models/ApplePayDirectDomainAllowListItem.php
> +        if (strpos($value, 'http') !== 0) {
i think you could use the sanitizer in here?

2024-07-11 06:45 UTC, boxblinkracer commented on src/Service/SettingsService.php
> +    const APPLE_PAY_DIRECT_DOMAIN_ALLOW_LIST = 'applePayDirectDomainAllowList';
glaub das ist nicht notwendig

2024-07-11 06:46 UTC, boxblinkracer commented on src/Service/SettingsService.php
> +    const APPLE_PAY_DIRECT_DOMAIN_ALLOW_LIST = 'applePayDirectDomainAllowList';
aaaa, MollieSettingsStruct is the correct one

2024-07-11 07:10 UTC, boxblinkracer requested changes
comments

2024-07-11 11:18 UTC, boxblinkracer commented on tests/PHPUnit/Components/ApplePayDirect/Gateways/ApplePayDirectDomainAllowListGatewayTest.php
> +        $struct = $this->createConfiguredMock(MollieSettingStruct::class, ['getApplePayDirectDomainAllowList' => '']);
just a styling thing, but maybe something for the future
you dont always need to mock things
you could just create a new setting struct, set your value and use it :)

2024-07-11 11:19 UTC, boxblinkracer commented on tests/PHPUnit/Components/ApplePayDirect/Services/ApplePayDirectDomainSanitizerTest.php
> +            'removes http value if provided' => ['http://example.com', 'example.com'],
can you add a subdomain too? that would be good

2024-07-11 11:20 UTC, boxblinkracer approved these changes

2024-07-26 06:22 UTC, merged