PISHPS-311: added custom event and cart collector for subscriptions
mollie/Shopware6 pull request #801
Opened 2024-08-07 12:17 UTC by m-muxfeld-diw

2024-08-08 05:45 UTC, m-muxfeld-diw commented
@BlackScorp can be tested with this patch

```sh
Index: src/Subscriber/OrderDeliverySubscriber.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Subscriber/OrderDeliverySubscriber.php b/src/Subscriber/OrderDeliverySubscriber.php
--- a/src/Subscriber/OrderDeliverySubscriber.php	(revision 9e1fa93e083290440433789acf788843ef0cf41a)
+++ b/src/Subscriber/OrderDeliverySubscriber.php	(date 1723028422423)
@@ -3,6 +3,7 @@
 namespace Kiener\MolliePayments\Subscriber;
 
 use Kiener\MolliePayments\Components\ShipmentManager\ShipmentManager;
+use Kiener\MolliePayments\Event\MollieSubscriptionCartItemAddedEvent;
 use Kiener\MolliePayments\Repository\OrderTransaction\OrderTransactionRepositoryInterface;
 use Kiener\MolliePayments\Service\OrderService;
 use Kiener\MolliePayments\Service\SettingsService;
@@ -64,6 +65,7 @@
     {
         return [
             'state_machine.order_delivery.state_changed' => 'onOrderDeliveryChanged',
+            MollieSubscriptionCartItemAddedEvent::class => 'test'
         ];
     }
 
@@ -123,4 +125,9 @@
             return;
         }
     }
+
+    public function test(MollieSubscriptionCartItemAddedEvent $event)
+    {
+        $a = 1;
+    }
 }
```

2024-08-08 08:05 UTC, BlackScorp requested changes

2024-08-08 08:05 UTC, BlackScorp commented on src/Service/Cart/Subscription/SubscriptionCartCollector.php
> +        $customFields = $lineItem->getPayloadValue('customFields');
can you use here LineItemAttributes the class accepts lineItem as constructor parameter and has a method to define if the line item is subscription

2024-08-21 05:59 UTC, BlackScorp requested changes

2024-08-21 09:32 UTC, merged