PISHPS-304: added OrderTagService
mollie/Shopware6 pull request #821
Opened 2024-09-03 08:47 UTC by m-muxfeld-diw

2024-09-03 13:30 UTC, BlackScorp requested changes

2024-09-03 13:30 UTC, BlackScorp commented on src/Service/Tags/OrderTagService.php
> +            throw CouldNotTagOrderException::forSubscription(sprintf('Tag with name "%s" and ID "%s" not found', $subscriptionTag->getName(), $subscriptionTag->getId()));
can you just log the info instead of throwing exception here? sometimes customers likes to delete tags, just in case that buying subscription still will work without tags

2024-09-03 13:30 UTC, BlackScorp commented on src/Service/Tags/OrderTagService.php
> +        $criteria->addFilter(new EqualsFilter('id', $subscriptionTag->getId()));
can you use here the tag name, merchants can delete and create tags on the fly

2024-09-03 13:30 UTC, BlackScorp commented on src/Service/Tags/OrderTagService.php
> +        return ['id' => $tag->getId(),];
is this comma intentional?

2024-09-04 06:47 UTC, m-muxfeld-diw commented on src/Service/Tags/OrderTagService.php
> +        return ['id' => $tag->getId(),];
It was, but I don't mind removing it

2024-09-04 06:56 UTC, merged