Feature/payment refunds
mollie/Shopware6 pull request #89
Opened 2021-03-15 16:38 UTC by milan-kiener

Refactored refunds to use payment refunds instead of order refunds. Refunded amount is now also fetched from Mollie instead of trying to keep track of it in Shopware.

2021-03-24 10:08 UTC, schmitzcarsten requested changes
unfortuantely my tests haven't been successful. After a while the mollie refund button stayed disabled and never came back to enabled status !

Please add unit tests and do test everything on functionality

I'm missing a view of refund history. Never showed up in my tests.

2021-03-24 10:08 UTC, schmitzcarsten commented on src/Storefront/Controller/RefundController.php
> +        } catch (\Throwable $e) {
why are you catching throwables here?

2021-03-24 10:08 UTC, schmitzcarsten commented on src/Storefront/Controller/RefundController.php
>       * @Route("/api/v{version}/_action/mollie/refund",
for shopware 6.4 we need a route without versioning

add route without versioning

2021-03-29 12:30 UTC, milan-kiener commented on src/Resources/app/administration/src/module/mollie-payments/extension/sw-order/component/sw-order-line-items-grid/sw-order-line-items-grid.html.twig
> +            <div align="right">
But, that's a block I added so there is no parent. Would you rather I'd remove the block tag to avoid confusion?

2021-03-29 12:31 UTC, milan-kiener commented on src/Resources/app/administration/src/module/mollie-payments/extension/sw-order/component/sw-order-line-items-grid/sw-order-line-items-grid.html.twig
> +                        <sw-button class="sw-order-line-items-grid__actions-container-add-product-btn"
I indeed forgot to rename the classname to indicate the refund button, it is a copy of the add product button after all. The rest of the naming is in line with the other elements in default Shopware however.

2021-03-29 15:55 UTC, milan-kiener commented on src/Service/RefundService.php
> +        return $paidPayments[0];
We are filtering for payments with status paid (and authorized has also been added already) a few lines above this. $paidPayments will therefor always have the paid (or authorized) payment at index 0. If $paidPayments is empty (aka there are no paid or authorized payments yet), this function returns null.
Furthermore, you do the same in the Shopware 5 plugin, looping through all payments and breaking out of it if the payment is either paid or authorized.

2021-03-29 15:56 UTC, milan-kiener commented on src/Service/RefundService.php
> +        $payment = $this->getPaymentForOrder($order);
This function returns the amount already refunded. It does not return a refund.

2021-03-30 16:41 UTC, milan-kiener commented on src/Resources/app/administration/src/module/mollie-payments/extension/sw-order/view/sw-order-detail-base/sw-order-detail-base.html.twig
> +    <dt v-if="refundedAmount > 0"><strong>{{ $tc('sw-order.detailExtended.totalRefunds') }}</strong></dt>
Mollie seems to only update the "amountRefunded" variable when the refund has been processed. So on an order of € 50, you can refund a maximum of € 75. If you refund, say, € 30, Mollie will still say you've refunded nothing until the refund has been processed. They will update the "amountRemaining" variable to say € 45 instead of the € 75, however.

I've added an additional line that specifies the amount awaiting to be processed.

2021-05-27 08:45 UTC, closed without merging