NTR: add PHPInsight + CS Fixer
mollie/Shopware6 pull request #91
Opened 2021-03-26 12:58 UTC by boxblinkracer

add cs fixer (+ pipeline)
add make pr command to auto fix and run for contributors
add php insights with minimum code quality checks + pipeline

please note, somehow phpinsights doesnt have fixing options for developers (only in version 2 regarding to documentation, but latest 1.14...weird)

the good thing is, the output might be weird, but the minimum code quality checks (so the exit value) all work

2021-03-26 17:03 UTC, barbieswimcrew requested changes

2021-03-26 17:03 UTC, barbieswimcrew commented on .php_cs.php
> +    );
please consider no newline warning

2021-03-26 20:18 UTC, schmitzcarsten approved these changes

2021-04-01 06:14 UTC, schmitzcarsten approved these changes

2021-04-01 06:20 UTC, merged