[MOL-368] fix apple pay
mollie/Shopware6 pull request #97
Opened 2021-04-07 15:20 UTC by StephanAltmann85

2021-04-09 07:36 UTC, schmitzcarsten approved these changes

2021-04-09 07:37 UTC, schmitzcarsten requested changes
Is the pull request complete? You told me that there is existing a problem? I don't know if it's solved here?

2021-04-09 08:53 UTC, StephanAltmann85 commented
> Is the pull request complete? You told me that there is existing a problem? I don't know if it's solved here?

The webhook controller will still change the shopware payment method to creditcard (if creditcard has been used with Apple Pay) afterwards. The fix would be to delete the update procedure in src/Helper/PaymentStatusHelper.php (Line 183). 

I don't understand why this has been implemented. For me it makes no sense at all, but I cannot make the decision for removing it.

2021-04-20 12:18 UTC, schmitzcarsten approved these changes

2021-04-20 12:55 UTC, boxblinkracer commented on src/Helper/PaymentStatusHelper.php
> +            && $this->paymentMethodService->isPaidApplePayTransaction($transaction, $mollieOrder) === false) {
wouldnt it be correct to say "ifApplePay" transaction
otherwise it would still update it if its a failed apple pay method? then its suddenly credit card

so i guess the combination with "paid" is wrong?

2021-04-20 12:56 UTC, boxblinkracer commented on src/MolliePayments.php
> +            $domainVerificationService = $this->container->get(ApplePayDomainVerificationService::class);
why is it wrapped in an active flag?
what if the inactive plugin gets updated, then no download happens.
afterwards i would activate the plugin...does the postInstall from below get called?! if not, then the file is missing

2021-04-20 12:58 UTC, boxblinkracer commented on src/Service/ApplePayDomainVerificationService.php
> +        if($this->filesystem->has(self::LOCAL_FILE) === true) {
attention, if the signature of the file changes, it wouldnt be possible to update it without removing it.
i would rather always download the file

2021-04-20 12:59 UTC, StephanAltmann85 commented on src/Helper/PaymentStatusHelper.php
> +            && $this->paymentMethodService->isPaidApplePayTransaction($transaction, $mollieOrder) === false) {
No, otherwise every ApplePay-Transaction would get excluded from MollieErrorHandling. A successfull ApplePayDirect transaction always should be paid.

2021-04-20 12:59 UTC, StephanAltmann85 commented on src/MolliePayments.php
> +            $domainVerificationService = $this->container->get(ApplePayDomainVerificationService::class);
If plugin isn't active the service is not available.

2021-04-20 13:01 UTC, StephanAltmann85 commented on src/Service/ApplePayDomainVerificationService.php
> +        if($this->filesystem->has(self::LOCAL_FILE) === true) {
But it would also overwrite custom domain verification files.

2021-04-20 13:02 UTC, boxblinkracer commented on src/Service/PaymentMethodService.php
> -        /** @var string $mediaId */
what is going on in this file?
is that related to an apple pay fix?

2021-04-20 13:02 UTC, boxblinkracer commented on src/Service/PaymentMethodService.php
> +        return $transaction->getPaymentMethod()->getHandlerIdentifier() === ApplePayPayment::class && $mollieOrder->isPaid() === true;
what about apple pay direct? is it covered with this in sw6?
(sw5 has 2 different payment methods)

2021-04-20 13:03 UTC, StephanAltmann85 commented on src/Service/PaymentMethodService.php
> +        return $transaction->getPaymentMethod()->getHandlerIdentifier() === ApplePayPayment::class && $mollieOrder->isPaid() === true;
Only 1 payment method.

2021-04-20 13:03 UTC, StephanAltmann85 commented on src/Service/PaymentMethodService.php
> -        /** @var string $mediaId */
No, just code clean up.

2021-04-20 13:04 UTC, boxblinkracer commented on src/Service/ApplePayDomainVerificationService.php
> +        $this->filesystem->put(self::LOCAL_FILE, $content);
just to double check,...its available in the public docroot right?

2021-04-20 13:04 UTC, boxblinkracer commented on src/Service/ApplePayDomainVerificationService.php
> +    private const URL_FILE = 'https://www.mollie.com/.well-known/apple-developer-merchantid-domain-association';
please create unit tests to avoid accidental changes of these values, thx

2021-04-20 13:04 UTC, boxblinkracer requested changes
see comments, thx

2021-04-20 13:09 UTC, StephanAltmann85 commented on src/Service/ApplePayDomainVerificationService.php
> +        $this->filesystem->put(self::LOCAL_FILE, $content);
Yes

2021-04-20 13:31 UTC, StephanAltmann85 commented on src/Service/ApplePayDomainVerificationService.php
> +    private const URL_FILE = 'https://www.mollie.com/.well-known/apple-developer-merchantid-domain-association';
Done

2021-04-20 13:47 UTC, boxblinkracer commented on src/Helper/PaymentStatusHelper.php
> +            && $this->paymentMethodService->isPaidApplePayTransaction($transaction, $mollieOrder) === false) {
isnt this about avoiding that apple pay gets converted into credit card through a webhook?
yes every would excluded, but that is the aim as far as i know?!
@schmitzcarsten  please verify what you need

2021-04-20 13:48 UTC, boxblinkracer commented on src/MolliePayments.php
> +            $domainVerificationService = $this->container->get(ApplePayDomainVerificationService::class);
yes but that was more the secondary question
what about the main problem

2021-04-20 13:49 UTC, boxblinkracer commented on src/Service/ApplePayDomainVerificationService.php
> +        if($this->filesystem->has(self::LOCAL_FILE) === true) {
custom domain files?!

2021-04-20 13:54 UTC, boxblinkracer commented on tests/Service/ApplePayDomainVerificationServiceTest.php
> +        $content = file_get_contents(ApplePayDomainVerificationService::URL_FILE);
this test does not make any sense

please just verify the constant that the download URL is correct

2021-04-20 13:54 UTC, boxblinkracer commented on tests/Fixtures/apple-developer-merchantid-domain-association
> +7B227073704964223A2244394337463730314338433646324336463344363536433039393434453332323030423137364631353245353844393134304331433533414138323436453630222C2276657273696F6E223A312C22637265617465644F6E223
please remove this

2021-04-20 13:57 UTC, StephanAltmann85 commented on tests/Service/ApplePayDomainVerificationServiceTest.php
> +        $content = file_get_contents(ApplePayDomainVerificationService::URL_FILE);
Yes it makes sense, because it is testing that file url is valid and the file has not changed...

2021-04-20 14:00 UTC, boxblinkracer commented on tests/Service/ApplePayDomainVerificationServiceTest.php
> +        $content = file_get_contents(ApplePayDomainVerificationService::URL_FILE);
the file CAN change as mentioned above
and unit tests need to be able to run offline

2021-04-20 14:07 UTC, StephanAltmann85 commented on tests/Fixtures/apple-developer-merchantid-domain-association
> +7B227073704964223A2244394337463730314338433646324336463344363536433039393434453332323030423137364631353245353844393134304331433533414138323436453630222C2276657273696F6E223A312C22637265617465644F6E223
Done

2021-04-20 14:07 UTC, StephanAltmann85 commented on tests/Service/ApplePayDomainVerificationServiceTest.php
> +        $content = file_get_contents(ApplePayDomainVerificationService::URL_FILE);
done

2021-04-20 14:10 UTC, StephanAltmann85 commented on src/MolliePayments.php
> +            $domainVerificationService = $this->container->get(ApplePayDomainVerificationService::class);
File will be downloaded on activation.

2021-04-20 14:25 UTC, boxblinkracer commented on src/MolliePayments.php
> +            $domainVerificationService = $this->container->get(ApplePayDomainVerificationService::class);
ah perfect, github diff change made it look like its in postInstall :D all good thx

2021-04-20 14:27 UTC, boxblinkracer commented on tests/Service/ApplePayDomainVerificationServiceTest.php
> +        self::assertEquals(ApplePayDomainVerificationService::URL_FILE, self::URL_FILE);
thank you, way better
please switch arguments, its (expected, actual)

2021-04-20 14:27 UTC, StephanAltmann85 commented on src/MolliePayments.php
> +            $domainVerificationService = $this->container->get(ApplePayDomainVerificationService::class);
Ich bin nach dem Kommentar auch darauf reingefallen.

2021-04-20 14:30 UTC, StephanAltmann85 commented on tests/Service/ApplePayDomainVerificationServiceTest.php
> +        self::assertEquals(ApplePayDomainVerificationService::URL_FILE, self::URL_FILE);
oh, ja

2021-04-20 17:09 UTC, barbieswimcrew approved these changes

2021-04-27 15:24 UTC, schmitzcarsten requested changes

2021-04-27 15:29 UTC, StephanAltmann85 commented
Done

2021-05-14 06:08 UTC, schmitzcarsten approved these changes

2021-05-14 06:10 UTC, schmitzcarsten approved these changes

2021-05-17 07:08 UTC, merged