MOL-354: Improved Order State Handling
mollie/Shopware6 pull request #99
Opened 2021-04-12 08:45 UTC by ThLind

Improved Order State Handling. In the old state handling unnecessary and failing transitions were executed to bring the order in known states. Now only perform necessary transitions and avoid failing transitions.

2021-04-14 08:24 UTC, schmitzcarsten requested changes

2021-04-14 08:24 UTC, schmitzcarsten commented on src/Helper/OrderTransitionHelper.php
> +class OrderTransitionHelper implements OrderTransitionHelperInterface
Please don't use class names like helper. Find a meaningful service name like TransitionOrderStatusService or something like that. Helper could be everything and nothing.

2021-04-14 08:24 UTC, schmitzcarsten commented on src/Helper/OrderStateHelper.php
>  class OrderStateHelper
Please don't use class names like helper. Find a meaningful service name like ChangeOrderState or something like that. Helper could be everything and nothing.

2021-04-14 08:24 UTC, schmitzcarsten commented on src/Helper/OrderTransitionHelperInterface.php
> +interface OrderTransitionHelperInterface
find a better name

2021-04-14 08:24 UTC, schmitzcarsten commented on tests/Fakes/FakeOrderTransitionHelper.php
> +class FakeOrderTransitionHelper implements OrderTransitionHelperInterface
rename accordingly to the class that is tested

2021-04-14 08:24 UTC, schmitzcarsten commented on tests/Helper/OrderStateHelperTest.php
> +class OrderStateHelperTest extends TestCase
rename accordingly to the class that is tested

2021-04-14 08:24 UTC, schmitzcarsten commented on tests/Helper/OrderTransitionHelperTest.php
> +class OrderTransitionHelperTest extends TestCase
rename accordingly to the class that is tested

2021-04-14 12:45 UTC, ThLind commented on src/Helper/OrderStateHelper.php
>  class OrderStateHelper
Thank the earlier naming for this ;-) Just didn't want to change this everywhere it's used and leave this for your big refactoring, but if you want I can do it the next time I do work on this.

2021-04-14 14:48 UTC, schmitzcarsten commented on src/Helper/OrderStateHelper.php
>  class OrderStateHelper
yes please. Move it to a suitable namespace and rename it. 
But only such classes that you have added or updated. Then it should not be much work

2021-04-16 06:53 UTC, schmitzcarsten approved these changes

2021-04-16 11:47 UTC, barbieswimcrew approved these changes

2021-04-16 12:24 UTC, merged